[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions/"

[dev]
  targetPort = 8080
  autoLaunch = false
  command = "vite --host localhost --port 8080"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[functions."autopost-background"]
  schedule = "*/15 * * * *"
  included_files=["functions/emails/*.liquid"]

[functions."cron"]
  included_files=["functions/emails/*.liquid"]

[functions."submission-created"]
  included_files=["functions/emails/*.liquid"]

[functions."approve"]
  included_files=["functions/emails/*.liquid"]

[functions."profile"]
  included_files=["functions/emails/*.liquid"]

[[plugins]]
  package = 'netlify-plugin-contextual-env'
